language: php

php:
- 5.3

env:
  matrix:
    - TEST_SUITE=UnitTests MYSQL_ADAPTER=PDO_MYSQL
    - TEST_SUITE=PluginTests MYSQL_ADAPTER=PDO_MYSQL
  global:
    - TEST_PLUGIN_NAME=SimpleSysMon
    - TEST_PLUGIN_REPO="job963/SimpleSysMon.git"
    - TEST_PLUGIN_VERSION=0.2.1
    - TEST_PIWIK_VERISON=2.10.0-b6
    - TEST_PLUGIN_TAGNAME=v0.2.1
    - secure: "hQyh+ezFGj5VXn/1X/O5D8p7w883NVA9dZl1NvEuWvV1xxIldL0YPRUm5CpeaCzASropMwHa7/qpiwWLRQGkGYIrl3JsMwCWTjy6bUqaCY3IbohD9dQZgnn7E5qathqhEknjIVCPwaFFPnpRE2OD8GCWf2hsoLxlKY/KXOU00wE="

script: ./travis.sh

install:
  - git clone https://github.com/piwik/piwik.git piwik
  - cd piwik
  - git checkout "$TEST_PIWIK_VERISON"
  - git submodule init
  - git submodule update
  - composer install
  - rm -rf "plugins/$TEST_PLUGIN_NAME"
  - git clone "https://github.com/$TEST_PLUGIN_REPO" "plugins/$TEST_PLUGIN_NAME"
  - cd "plugins/$TEST_PLUGIN_NAME"
  - git checkout "$TEST_PLUGIN_TAGNAME"
  - cd ../../../

before_script:
  - cd piwik
  - uname -a
  - date
  - mysql -e 'create database piwik_tests;'
  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - cp ../activateplugin.php .
  - php activateplugin.php $TEST_PLUGIN_NAME
  - cd ../

after_script:
  - cat /var/log/nginx/error.log
  - cat $TRAVIS_BUILD_DIR/piwik/tmp/php-fpm.log
  - cat $TRAVIS_BUILD_DIR/piwik/tmp/logs/logger_message.htm

notifications:
  email:
    - marketplace@piwik.org
