language: php

# We want to test against PHP 5.3/5.4/5.5
# TODO activate plugin
php:
- 5.3

env:
  matrix:
    - TEST_SUITE=CoreTests
  global:
    - secure: "hQyh+ezFGj5VXn/1X/O5D8p7w883NVA9dZl1NvEuWvV1xxIldL0YPRUm5CpeaCzASropMwHa7/qpiwWLRQGkGYIrl3JsMwCWTjy6bUqaCY3IbohD9dQZgnn7E5qathqhEknjIVCPwaFFPnpRE2OD8GCWf2hsoLxlKY/KXOU00wE="

script: ./travis.sh

install:
  - git clone https://github.com/piwik/piwik.git piwik
  - cd piwik
  - git checkout 2.0-a6
  - composer install
  - git clone https://github.com/tsteur/piwik-evil-plugin.git plugins/Evil
  - cd plugins/Evil/
  - git checkout 1.0.1
  - cd ../../../

before_script:
  - cd piwik
  - uname -a
  - date
  - mysql -e 'create database piwik_test;'
  - ./tests/travis/prepare.sh
  - ./tests/travis/setup_webserver.sh
  - cp ../activateplugin.php .
  - php activateplugin.php Evil
  - cd ../

after_script:
  - cat /var/log/nginx/error.log
  - cat $TRAVIS_BUILD_DIR/../piwik/tmp/php-fpm.log
  - cat $TRAVIS_BUILD_DIR/../piwik/tmp/logs/logger_message.htm

notifications:
  email:
    - marketplace@piwik.org
